<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
好玩的登录页面<!DOCTYPE html>
<!-- saved from url=(0028)https://dash.readme.io/login -->
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="https://www.facebook.com/2008/fbml" itemscope="itemscope" itemtype="http://schema.org/Product"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"

                            ;><title>ReadMe.io : Crowdsource Your Developer Hub</title><meta name="keywords" content="readme,developer hub,documentation"><meta name="description" content="A collaborative developer hub for your API or code."><meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;"><meta name="google-site-verification" content="02bkTvw0S-_3l_qaBCNepYM-Belw0uZwoS04h85_tAQ"><link href="https://dash.readme.io/favicon.ico" rel="shortcut icon" type="image/x-icon"><!--Opengraph tags--><meta property="fb:app_id" content="293989217296609"><meta property="og:title" content="ReadMe.io : Collaborative Developer Hub"><meta property="og:description" content="A collaborative developer hub for your API or code."><meta property="og:url" content="http://readme.io"><meta property="og:image" content="http://readme.io/img/image.png?1"><meta property="og:site_name" content="ReadMe.io"><meta property="fb:admins" content="1037213945"><meta name="csrf-token" content="GHeQuGIhq7VYDx2c6tWqr9S2B2jGhLIs8AmI4="><!-- Application styles--><link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700|Roboto+Slab:300,700" rel="stylesheet" type="text/css"><link rel="stylesheet" href="https://dash.readme.io/css/bundle-home.css?1423168424086"><!--if lt IE 9script(src="//html5shim.googlecode.com/svn/trunk/html5.js")
--><script async="" src="./ReadMe.io   Crowdsource Your Developer Hub_files/analytics.js"></script><script type="text/javascript" async="" src="./ReadMe.io   Crowdsource Your Developer Hub_files/heap.js"></script><script>window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["identify","track"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
heap.load('1752122866');</script></head><body id="login" class="unloaded"><div class="wrapper"><header><nav role="navigation" class="navbar navbar-default"><div class="container"><!-- Brand and toggle get grouped for better mobile display --><div class="navbar-header"><button type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" class="navbar-toggle"><span class="sr-only">Toggle Navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="https://dash.readme.io/" class="navbar-brand">ReadMe.io</a></div><!-- Collect the nav links, forms, and other content for toggling --><div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse"><ul class="nav navbar-nav"><li><!--a(href="/features")| Features
span--></li><li><a href="https://dash.readme.io/#scroll-pricing" class="scroll">Pricing<span></span></a></li><li><a href="https://dash.readme.io/#scroll-examples" class="scroll">Examples<span></span></a></li><li><a href="https://readme.io/blog">Blog<span></span></a></li></ul><ul class="nav navbar-nav navbar-right"><li><a href="./ReadMe.io   Crowdsource Your Developer Hub_files/ReadMe.io   Crowdsource Your Developer Hub.html" class="login-top active">Log In<span></span></a></li><li class="signup-top-parent"><a href="https://dash.readme.io/signup" class="signup-top">Sign Up<span></span></a></li></ul></div></div></nav></header><div class="login"><form action="https://dash.readme.io/users/session" method="post" class="container offset1 loginform"><div id="owl-login"><div class="hand"></div><div class="hand hand-r"></div><div class="arms"><div class="arm"></div><div class="arm arm-r"></div></div></div><div class="pad"><input type="hidden" name="_csrf" value="GHeQuGIhq7VYDx2c6tWqr9S2B2jGhLIs8AmI4="><div class="control-group"><div class="controls"><label for="email" class="control-label fa fa-envelope"></label><input id="email" type="email" name="email" placeholder="Email" tabindex="1" autofocus="autofocus" class="form-control input-medium"></div></div><div class="control-group"><div class="controls"><label for="password" class="control-label fa fa-asterisk"></label><input id="password" type="password" name="password" placeholder="Password" tabindex="2" class="form-control input-medium"></div></div></div><div class="form-actions"><a href="https://dash.readme.io/forgot/" tabindex="5" class="btn pull-left btn-link text-muted">Forgot password?</a><a href="https://dash.readme.io/signup" tabindex="6" class="btn btn-link text-muted">Sign Up</a><button type="submit" tabindex="4" class="btn btn-primary">Login</button></div></form></div></div><script src="./ReadMe.io   Crowdsource Your Developer Hub_files/bundle-home.js"></script><script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-52479696-1', 'auto');
ga('send', 'pageview');</script><iframe name="filepicker_comm_iframe" id="filepicker_comm_iframe" src="./ReadMe.io   Crowdsource Your Developer Hub_files/saved_resource.html" style="display: none;"></iframe><iframe name="fpapi_comm_iframe" id="fpapi_comm_iframe" src="./ReadMe.io   Crowdsource Your Developer Hub_files/saved_resource(1).html" style="display: none;"></iframe></body></html>                        